export enum FulfilmentJobStatus {
  PENDING_KIOSK = 'PendingKiosk',
  PENDING_ASSIGNMENT = 'PendingAssignment',
  OFFERED = 'Offered',
  ASSIGNED = 'Assigned',
  EN_ROUTE_TO_KIOSK = 'EnRouteToKiosk',
  AT_KIOSK = 'AtKiosk',
  PENDING_PRINT = 'PendingPrint',
  AWAITING_POLICY_NUMBER = 'AwaitingPolicyNumber',
  AWAITING_PRINT = 'AwaitingPrint',
  PRINT_FAILED = 'PrintFailed',
  READY_FOR_COLLECTION = 'ReadyForCollection',
  COLLECTED = 'Collected',
  EN_ROUTE_TO_HOLDER = 'EnRouteToHolder',
  AT_HOLDER = 'AtHolder',
  DELIVERY_FAILED = 'DeliveryFailed',
  RETURNING_TO_KIOSK = 'ReturningToKiosk',
  RETURNED = 'Returned',
  AWAITING_PICKUP = 'AwaitingPickup',
  COMPLETED = 'Completed',
  CANCELLED = 'Cancelled',
  EXPIRED = 'Expired',
}
