export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  PAYMENT_VERIFICATION_REQUIRED = 'PAYMENT_VERIFICATION_REQUIRED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  GRACE_PERIOD = 'GRACE_PERIOD',
  SUSPENDED = 'SUSPENDED',
}
